services:
  bot:
    build: .
    container_name: s9my-auto-deposit-bot
    restart: always
    networks:
      - coolify
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://s9my:s9mypass@dw869cxr65y2ucja40f0e04n:5432/s9my_bot
      - TZ=Asia/Kuala_Lumpur
      - LOG_LEVEL=INFO
      - PUBLIC_BASE_URL=${PUBLIC_BASE_URL}
      - BOT_TOKEN=${BOT_TOKEN}
      - OWNER_ID=${OWNER_ID}
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'

networks:
  coolify:
    external: true
