services:
  bot:
    build: .
    container_name: s9my-auto-deposit-bot
    restart: always
    environment:
      - PORT=8080
      - 'DATABASE_URL=postgresql://s9my:s9mypass@10.0.1.19:5432/s9my_bot'
      - TZ=Asia/Kuala_Lumpur
      - LOG_LEVEL=INFO
      - 'PUBLIC_BASE_URL=${PUBLIC_BASE_URL}'
      - 'BOT_TOKEN=${BOT_TOKEN}'
      - 'ADMIN_IDS=${ADMIN_IDS}'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
